const { formatMoney, formatDate, escape, brand, baseStyles } = require('./_shared');

const renderQuote = (quote) => {
  const b = brand();
  const client = quote.client || {};
  const lines = quote.lines || [];

  const linesHtml = lines.map((line) => `
    <tr>
      <td>
        <strong>${escape(line.description)}</strong>
        ${line.code ? `<br/><small style="color:#5a6270">${escape(line.code)}</small>` : ''}
      </td>
      <td class="right">${line.quantity || 1}</td>
      <td class="right">${formatMoney(line.sellRate, line.currency)}</td>
      <td class="right"><strong>${formatMoney((line.sellRate || 0) * (line.quantity || 1), line.currency)}</strong></td>
    </tr>
  `).join('');

  const containersHtml = (quote.containers || [])
    .map((c) => `${c.quantity}× ${escape(c.type)}`)
    .join(', ');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Quote ${escape(quote.quoteNumber)}</title>
<style>${baseStyles(b.color)}</style>
</head>
<body>
  <div class="doc">
    <div class="header">
      <div>
        <div class="brand-name">${escape(b.name)}</div>
        <div class="brand-meta">
          ${escape(b.address)}<br/>
          ${b.phone ? `Tel: ${escape(b.phone)} · ` : ''}${escape(b.email)}<br/>
          ${escape(b.website)}
        </div>
      </div>
      <div class="doc-title">
        <h1>Quotation</h1>
        <div class="number">${escape(quote.quoteNumber)}${quote.revision > 1 ? ` (R${quote.revision})` : ''}</div>
        <div style="font-size:11px;color:#5a6270;margin-top:6px">
          Issued ${formatDate(quote.createdAt)}<br/>
          Valid until <strong>${formatDate(quote.validUntil)}</strong>
        </div>
      </div>
    </div>

    <div class="meta-grid">
      <div class="meta-block">
        <h3>Quoted To</h3>
        <div class="value">
          <strong>${escape(client.companyName || 'Customer')}</strong>
          ${client.clientCode ? `${escape(client.clientCode)}<br/>` : ''}
          ${client.email ? `${escape(client.email)}<br/>` : ''}
          ${client.phone ? `${escape(client.phone)}` : ''}
        </div>
      </div>
      <div class="meta-block">
        <h3>Shipment Details</h3>
        <div class="value">
          <strong>${escape((quote.mode || '').toUpperCase())} · ${escape(quote.type || '')}</strong>
          ${quote.direction ? `${escape(quote.direction)}<br/>` : ''}
          ${quote.origin?.name ? `From: ${escape(quote.origin.name)}${quote.origin.code ? ` (${escape(quote.origin.code)})` : ''}<br/>` : ''}
          ${quote.destination?.name ? `To: ${escape(quote.destination.name)}${quote.destination.code ? ` (${escape(quote.destination.code)})` : ''}<br/>` : ''}
          ${quote.incoterm ? `Incoterm: <strong>${escape(quote.incoterm)}</strong><br/>` : ''}
          ${quote.transitTimeDays ? `Transit: ~${quote.transitTimeDays} days<br/>` : ''}
          ${containersHtml ? `Containers: ${containersHtml}<br/>` : ''}
          ${quote.cargoDescription ? `<br/><em>${escape(quote.cargoDescription)}</em>` : ''}
        </div>
      </div>
    </div>

    <table class="lines">
      <thead>
        <tr>
          <th>Description</th>
          <th class="right" style="width:70px">Qty</th>
          <th class="right" style="width:110px">Rate</th>
          <th class="right" style="width:120px">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${linesHtml || `<tr><td colspan="4" style="text-align:center;padding:40px;color:#5a6270">No charges</td></tr>`}
      </tbody>
    </table>

    <div class="totals">
      <table>
        <tr class="grand">
          <td class="label">Total</td>
          <td class="value">${formatMoney(quote.subtotalSell, quote.currency)}</td>
        </tr>
      </table>
    </div>

    <div class="footer">
      ${quote.notes ? `
        <div class="footer-section">
          <h4>Notes</h4>
          <div>${escape(quote.notes)}</div>
        </div>
      ` : ''}
      ${quote.termsAndConditions ? `
        <div class="footer-section">
          <h4>Terms &amp; Conditions</h4>
          <div>${escape(quote.termsAndConditions)}</div>
        </div>
      ` : `
        <div class="footer-section">
          <h4>Terms &amp; Conditions</h4>
          <div>This quotation is valid until ${formatDate(quote.validUntil)}. Rates are subject to space and equipment availability at the time of booking. Surcharges for fuel, currency, peak season, and security may apply per carrier tariff. All shipments are handled in accordance with our Standard Trading Conditions.</div>
        </div>
      `}
      <div class="footer-section" style="text-align:center;margin-top:24px;color:#9aa1ad">
        Generated by ${escape(b.name)} · ${formatDate(new Date())}
      </div>
    </div>
  </div>
</body>
</html>`;
};

module.exports = { renderQuote };
